### ISSUE TITLE
报错 for card in dylist["data"]["cards"]: KeyError: 'cards'

### ISSUE THREAD

**Issue by kendajiwaimai** [kushidou/bili-notice-hoshino#16]
![QQ截图20220810165927](https://user-images.githubusercontent.com/42399023/183860602-ee21df45-2987-41ab-bfe6-4ead11f45476.jpg)

看了一下，应该是阿b的api出问题了？？

**Comment by kendajiwaimai** [comment]
稍微改了一下，能用就行（bushi
![QQ图片20220810191722](https://user-images.githubusercontent.com/42399023/183888309-12ae905d-4088-453c-a7ab-a43dc790840a.png)

**Comment by kushidou** [comment]
感觉是网络问题（本地或者b站的api都有可能），程序进判断状态码不等于0时报错，没有处理这种状态码=0但是cards项丢失的情况。
