### ISSUE TITLE
取关之后会报这个错

### ISSUE THREAD

**Issue by SPLUS-VABLE** [kushidou/bili-notice-hoshino#17]
![image](https://user-images.githubusercontent.com/42440354/184048558-99f05412-14d5-4c38-8158-8dc409826d9b.png)

**Comment by kushidou** [comment]
重启机器人，这个clean_cache()能不能走过去？如果能走过去的话我知道问题在哪儿了。

**Comment by SPLUS-VABLE** [comment]
> 重启机器人，这个clean_cache()能不能走过去？如果能走过去的话我知道问题在哪儿了。

重启之后可以走过这个方法。

**Comment by kushidou** [comment]
代码已经更新，下载一下仓库里的代码。release要过一段时间才更新。

**Comment by SPLUS-VABLE** [comment]
> 代码已经更新，下载一下仓库里的代码。release要过一段时间才更新。
ok，谢谢大佬
