### ISSUE TITLE
Win server2019运行一段时间后会导致整个hoshino BOT无响应

### ISSUE THREAD

**Issue by mas-alone** [kushidou/bili-notice-hoshino#19]
排查了好久无法判断出问题。。只能在此发issue寻求帮助了。
服务器配置为4H8G，志强金牌。
`poll_time = 60` 其他设置均默认，运行一段时间(大概一小时?)，powershell页面就会卡住不动。
仅关注了一个UP，不知道其他老哥有无遇到类似问题。。

**Comment by mas-alone** [comment]
日志的话无报错..就是整个powershell卡死不动..

**Comment by kushidou** [comment]
屡次一段时间后就发生吗，还是说重启bot后powershell就直接卡死了？如果能复现，看看powershell是卡在任务触发中还是触发完后了。
另外如果可以的话提供一下这个up主的id，说不定ta的动态含有特殊内容，导致程序在意外的地方崩溃。

**Comment by mas-alone** [comment]
> 屡次一段时间后就发生吗，还是说重启bot后powershell就直接卡死了？如果能复现，看看powershell是卡在任务触发中还是触发完后了。 另外如果可以的话提供一下这个up主的id，说不定ta的动态含有特殊内容，导致程序在意外的地方崩溃。

`UID:8827561`
是每次一段时间后就发生，昨天的话运行了2个小时才卡死。
是在触发中的时候
![微信截图20220904082928](https://user-images.githubusercontent.com/52590027/188291892-92057553-c3ee-438f-b4b6-94fef9f190db.png)

**Comment by kushidou** [comment]
这个日志显示的与我不同，不仅出现了`[b站动态监视器]  INFO:`，还出现了一个`INFO in service: `，正常来讲应该只有一个，是不是您对Hoshino本身进行了修改？

正常情况终端里打印的日志应该是这样的：

![image](https://user-images.githubusercontent.com/26197294/188292404-3f7c73b6-a715-4e89-86f9-a8b2e0b3d6a6.png)

我待会儿会整一个程序测试这个uid，试一下能否复现这种情况。

**Comment by mas-alone** [comment]
> 这个日志显示的与我不同，不仅出现了`[b站动态监视器] INFO:`，还出现了一个`INFO in service: `，正常来讲应该只有一个，是不是您对Hoshino本身进行了修改？
> 
> 正常情况终端里打印的日志应该是这样的：
> 
> ![image](https://user-images.githubusercontent.com/26197294/188292404-3f7c73b6-a715-4e89-86f9-a8b2e0b3d6a6.png)
> 
> 我待会儿会整一个程序测试这个uid，试一下能否复现这种情况。

我重新git了一份hoshino，目前状态显示和您这边的一致了，我再运行一天看看还会不会。抱歉抱歉xD ><

**Comment by mas-alone** [comment]
应该是本地`hoshino`的问题..十分抱歉.
