### ISSUE TITLE
定时任务有问题，关注了大约20个up主，从推送任务开始不到一秒钟就结束了，并且没有正常推送

### ISSUE THREAD

**Issue by Explore617** [kushidou/bili-notice-hoshino#2]
![IMG_20220603_181408.jpg](https://user-images.githubusercontent.com/90906241/171835383-d5296da2-8f4d-4e71-a9a6-25bbe9dc264d.jpg)

**Comment by KnightK22** [comment]
大哥你这个怎么解决的，我的也是一样的完全没有推送
