### ISSUE TITLE
初次安装后，使用b站小号测试时报错 AttributeError: 'ImageDraw' object has no attribute 'rounded_rectangle'

### ISSUE THREAD

**Issue by KnightK22** [kushidou/bili-notice-hoshino#23]
![1](https://user-images.githubusercontent.com/57353187/221341804-c9259409-eb9d-43b4-b8a1-87700d88527a.png)
![2](https://user-images.githubusercontent.com/57353187/221341816-12d7f0ca-09da-455c-9d14-006a923efa48.png)
![3](https://user-images.githubusercontent.com/57353187/221341824-e025fd03-07af-4bf5-ad8b-ad6d3b7fdb49.png)
内容如图，请问这个该如何解决呢

**Comment by kushidou** [comment]
可能是安装的PIL模块有问题或者版本对不上，尝试使用pip 重新安装一次PIL。
这个rounded_rectangle 函数是PIL.ImageDraw自带的，这边报错“no attribute"，多半是PIL缺东西了。

**Comment by KnightK22** [comment]
> 可能是安装的PIL模块有问题或者版本对不上，尝试使用pip 重新安装一次PIL。 这个rounded_rectangle 函数是PIL.ImageDraw自带的，这边报错“no attribute"，多半是PIL缺东西了。

解决了，是我的pillow版本太低导致的，更新一下就好了
