### ISSUE TITLE
除了直播，其他内容没有正常推送

### ISSUE THREAD

**Issue by MiroticLAM** [kushidou/bili-notice-hoshino#25]
出现了类似 #2 的情况，关注2~5个人之后，除了直播外，没有推送其他内容，而且也没有报错。。
![QQ截图20230506175357](https://user-images.githubusercontent.com/79888484/236617181-5091d0eb-f056-4ce0-991d-5453a3bda67f.png)

**Comment by kushidou** [comment]
关注你自己的账号，然后发一条测试的动态，看一下1-2个轮询周期内插件有没有响应。

**Comment by MiroticLAM** [comment]
> 
![12](https://user-images.githubusercontent.com/79888484/236670130-94b0763d-4187-4026-83c9-b89e8af05cd0.png)

**Comment by MiroticLAM** [comment]
更正一下，目前的结果是超过3个人（不包含嘉然）就不会推送，取关到剩下3个人才会变正常

**Comment by kushidou** [comment]
可以将您目前的插件代码、配置、出问题的uppers文件和日志整体打包（也就是bili_notice_hoshino文件夹)发给我吗，邮箱small09@qq.com

**Comment by MiroticLAM** [comment]
> 可以将您目前的插件代码、配置、出问题的uppers文件和日志整体打包（也就是bili_notice_hoshino文件夹)发给我吗，邮箱[small09@qq.com](mailto:small09@qq.com)

已发送，麻烦大佬看看（鞠躬

**Comment by kushidou** [comment]
从取得的文件、日志和截图来看，应该确实是没有出错。我用你的`list.json`和`config.ini`，并且添加很多人后，依然是能够获取动态列表的。

对此，我在代码中添加了一些日志，如果可以的话麻烦拉取最新的'dymgr.py'文件，看一下是不是服务器或者网络问题。

测试的时候可以关注足够多的up主，然后删除`uppers`文件夹内所有的数字开头的json文件，并且重启机器人。启动后插件会从头拉取所有动态信息，这里加了新的日志会报告服务器返回的http code 和error code不正常的情况。

**Comment by MiroticLAM** [comment]
> 从取得的文件、日志和截图来看，应该确实是没有出错。我用你的`list.json`和`config.ini`，并且添加很多人后，依然是能够获取动态列表的。
> 
> 对此，我在代码中添加了一些日志，如果可以的话麻烦拉取最新的'dymgr.py'文件，看一下是不是服务器或者网络问题。
> 
> 测试的时候可以关注足够多的up主，然后删除`uppers`文件夹内所有的数字开头的json文件，并且重启机器人。启动后插件会从头拉取所有动态信息，这里加了新的日志会报告服务器返回的http code 和error code不正常的情况。

感谢大佬！确实是服务器的问题，我更新了windows的补丁后可以正常使用了！
