### ISSUE TITLE
关注up主总是提示服务器错误(code=-799, message=请求过于频繁，请稍后再试)

### ISSUE THREAD

**Issue by Baimotong** [kushidou/bili-notice-hoshino#26]
关注up主时一直报错
![image](https://github.com/kushidou/bili-notice-hoshino/assets/30062345/af80a490-d40e-4774-a368-09ceb8db5fe6)
![image](https://github.com/kushidou/bili-notice-hoshino/assets/30062345/b07d640d-ac5d-4249-93fc-369c48db71db)

在config.ini里设置了60了，仍然报这个错误
![image](https://github.com/kushidou/bili-notice-hoshino/assets/30062345/62eaf34b-409b-4350-8969-0837d604dd4b)
请问下应该如何解决？
另外插件是刚git clone的，应该是最新的，在重启hoshino后提示需要更新
![image](https://github.com/kushidou/bili-notice-hoshino/assets/30062345/4b3a9bca-54d8-4028-a871-0a0844aac4f2)
先谢谢大佬QAQ

**Comment by kushidou** [comment]
可能是你的服务器ip被风控了。你可以尝试用浏览器访问一下b站，看几个视频、逛一逛空间，或者等到第二天再尝试，等待期间不要访问b站的api。

关于更新的问题上次看日志发现了，但是我本机就是复现不出来，加上这玩意儿也就日志里面记录一下，就没管。你也可以在config里面关掉更新检查，最近基本没啥重大功能和重要bug修复，不更新也没啥大事儿。

我今天晚些时候增加一个不检查关注用户合法性的配置项，来应付一下这种情况。

**Comment by Baimotong** [comment]
好的，感谢大佬

**Comment by kushidou** [comment]
我到[bilibili-api-collect](https://github.com/SocialSisterYi/bilibili-API-collect/)看了一下，发现api改了，b站直接废弃了旧的API，而且新的api需要签名验证。
![image](https://github.com/kushidou/bili-notice-hoshino/assets/26197294/b8b6eea0-8cf0-4c16-a6fa-7b1afbe64fdb)

目前绕过查询直接添加到关注列表的功能已经实现了，但还需要适配新的api就不push代码了。

现在的建议是，直接到uppers/list.json把嘉然的uid和group改成你需要的。
