### ISSUE TITLE
现版本安装后启动提示TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Baimotong** [kushidou/bili-notice-hoshino#27]
大佬您好，我又来了。这边看到您更新了，所以想把模块删掉重新再安装，但安装好启动后就提示这个错误
TypeError: 'type' object is not subscriptable
![image](https://github.com/kushidou/bili-notice-hoshino/assets/30062345/d689ecb0-4ab6-4bff-a3d9-3d3311e0fc65)
内容如图，请问这个该如何解决呢？

**Comment by kushidou** [comment]
把res/wbi.py的这一行改一下

```python
def getWbiKeys() -> tuple[str, str]:
# 改成
def getWbiKeys():
```

也就是改成这样：
![image](https://github.com/kushidou/bili-notice-hoshino/assets/26197294/4c019dd9-0e4e-454b-8f5b-60e1bb9b56dd)

这个问题可能是由于python版本不同，我在python3.9上面是没有出现的

**Comment by Baimotong** [comment]
原来如此，我的是py3.8的，现在解决了，感谢大佬
