### ISSUE TITLE
文章类的动态会报错

### ISSUE THREAD

**Issue by Explore617** [kushidou/bili-notice-hoshino#3]
![IMG_20220603_190332.jpg](https://user-images.githubusercontent.com/90906241/171842020-3405bae7-bbc2-4e7f-a1ae-e41d1a7b6120.jpg)

**Comment by kushidou** [comment]
专栏文章类动态还在开发中，目前返回的是空，程序会报错。最近已经更新了跳过专栏动态等未开发动态的代码。
现在在外地出差中，功能开发和bug修复都会比较慢，请见谅。

**Comment by kushidou** [comment]
专栏文章类动态功能已经上线，更新后即可发送与专栏文章有关的内容。
