### ISSUE TITLE
BUG 缓存直播卡片图片时含有":"导致保存失败。

### ISSUE THREAD

**Issue by feelmaple** [kushidou/bili-notice-hoshino#31]
- 在配置项 `dycard_cache` 打开的情况下
https://github.com/kushidou/bili-notice-hoshino/blob/215c9ad3dd62f1ff5c5fe66b2f367d53731448af/config_example.ini#L38-L39
https://github.com/kushidou/bili-notice-hoshino/blob/215c9ad3dd62f1ff5c5fe66b2f367d53731448af/res/drawCard.py#L540-L543<br>日期里的冒号会导致文件保存失败

- `pillow` 最新版会报错 找不到 `ANTIALIAS` <br>百度了一下 需更换旧版本或将 `Image.ANTIALIAS` 替换为 `Image.Resampling.LANCZOS`

**Comment by kushidou** [comment]
感谢提醒，已经更改缓存图片的命名以规避问题。可以拉取最新的代码试一下。
