### ISSUE TITLE
这一串报错是什么意思

### ISSUE THREAD

**Issue by duoshoumiao** [kushidou/bili-notice-hoshino#39]
![Screenshot_2024-03-22-01-14-32-30_2665fb67b16260a8d818298cef8dc107.jpg](https://github.com/kushidou/bili-notice-hoshino/assets/94856184/2f18bd52-162b-4829-ab67-08c904bc4d2f)

**Comment by kushidou** [comment]
Duplicate of #40

**Comment by kushidou** [comment]
插件更新了获取动态的API接口，并完善了cookies认证机制。
