### ISSUE TITLE
需要一个关注列表展示

### ISSUE THREAD

**Issue by 1055169799** [kushidou/bili-notice-hoshino#5]
比如 查看本群关注的UP列表 

然后列出
本群关注的UP有：
UPid：叔叔、UPuid：123456

然后 查看所有关注的UP列表

群：123456
关注的UP有：
UPid：叔叔、UPuid：123456

群：789101
关注的UP有：
UPid：叔叔、UPuid：123456
UPid：阿姨、UPuid：234567

这样子的

不然到后面关注了哪些UP都不知道了，或者是取关UP时会漏了某个群

**Comment by 1055169799** [comment]
另外这个是不支持py3.9吗？一开始文件夹命名错误，路径报错了，修改后居然就没反应了，插件列表里都找不到这个插件。

**Comment by kushidou** [comment]
增加显示已关注的功能我记下了，将尽快添加这个功能。

python的版本兼容性，这个我没有多测试，可以试一下重新安装插件。目前我使用的版本是Linux + Python3.8.5，Hoshino也有一段时间没有更新过了。

另外“插件列表”功能是如何实现的？可能是我制作插件的时候没有考虑到被其他功能发现和管理的情况，可以介绍给我来适配一下。目前用`config/__bot__.py`来配置插件是可以加载的。

**Comment by 1055169799** [comment]
> 增加显示已关注的功能我记下了，将尽快添加这个功能。
> 
> python的版本兼容性，这个我没有多测试，可以试一下重新安装插件。目前我使用的版本是Linux + Python3.8.5，Hoshino也有一段时间没有更新过了。
> 
> 另外“插件列表”功能是如何实现的？可能是我制作插件的时候没有考虑到被其他功能发现和管理的情况，可以介绍给我来适配一下。目前用`config/__bot__.py`来配置插件是可以加载的。

插件列表是hoshino的自带功能，在一个机器人所在的群内，发送 lssv即可看到显示出来的插件，发送lssv -a可以看到所有的插件，包括隐藏的。
我之前用的也是py3.8，后面某个插件更新以后，需要3.9，然后我就升级了。我估计是这个问题，后面我再用3.8试试。

**Comment by kushidou** [comment]
**关注列表展示已经上线**，支持3种方式：
> "本群关注"
> 列出本群关注的所有UP主的昵称和UID。

> "所有关注"
> 仅机器人管理员可用
> 列出所有关注过的UP主（包括被所有群取关的）

> "所有群关注"
> 仅机器人管理员可用
> 按群分开，列出每个群的关注的UP主。

将关闭该Issue，对python3.9和lssv功能的兼容性将使用新issue跟踪。
