### ISSUE TITLE
这个是不支持py3.9吗？一开始文件夹命名错误，路径报错了，修改后居然就没反应了，插件列表里都找不到这个插件。

### ISSUE THREAD

**Issue by kushidou** [kushidou/bili-notice-hoshino#6]
另外这个是不支持py3.9吗？一开始文件夹命名错误，路径报错了，修改后居然就没反应了，插件列表里都找不到这个插件。

_Originally posted by @1055169799 in https://github.com/kushidou/bili-notice-hoshino/issues/5#issuecomment-1166433347_

**Comment by 1055169799** [comment]
我用了另一台服务器上部署的机器人，上面是3.8的py，打开之后，出现以下报错
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

————————————————————————
我屏蔽了其他的插件，仅保留机器人管理插件，运行出来的整个代码是这样的：

C:\Users\Administrator\Desktop\new-bot\haru-bot-setup>py -3.8 run.py
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
[2022-06-27 22:45:24,187 config] WARNING: Not found config of "bili_notice_hoshino"
[2022-06-27 22:45:24,187 config] WARNING: Not found config of "botchat"
[2022-06-27 22:45:24,187 config] INFO: Succeeded to load config of "groupmaster"
[2022-06-27 22:45:24,187 config] WARNING: Not found config of "botmanage"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\backends\backend_cairo.py", line 15, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import hoshino
  File "C:\Users\Administrator\Desktop\new-bot\haru-bot-setup\hoshino\__init__.py", line 55, in <module>
    from . import R
  File "C:\Users\Administrator\Desktop\new-bot\haru-bot-setup\hoshino\R.py", line 9, in <module>
    from hoshino import logger, util
  File "C:\Users\Administrator\Desktop\new-bot\haru-bot-setup\hoshino\util\__init__.py", line 13, in <module>
    from matplotlib import pyplot as plt
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\__init__.py", line 621, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\pyplot.py", line 257, in switch_backend
    switch_backend(candidate)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\pyplot.py", line 277, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\pyplot.py", line 278, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\backends\backend_gtk3agg.py", line 5, in <module>
    from . import backend_cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\backends\backend_cairo.py", line 21, in <module>
    import cairocffi as cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

C:\Users\Administrator\Desktop\new-bot\haru-bot-setup>pause
请按任意键继续. . .

——————————————————————

我并非程序员，不是很明白这是什么。不过你应该可以找到问题所在。

**Comment by kushidou** [comment]
> 我用了另一台服务器上部署的机器人，上面是3.8的py，打开之后，出现以下报错 raise OSError(error_message) # pragma: no cover OSError: no library called "cairo-2" was found no library called "cairo" was found no library called "libcairo-2" was found cannot load library 'libcairo.so.2': error 0x7e cannot load library 'libcairo.2.dylib': error 0x7e cannot load library 'libcairo-2.dll': error 0x7e
> 
>  ......

根据日志应该是缺少了依赖。

重新进入插件目录，`pip install -r requirements.txt`(pip的环境需要和当前环境一致)，看一下有没安装失败的，或者单独安装一下日志里报缺失的`cairo`  ==>  `pip install CairoSVG`

另外，日志好像还没走到加载插件的那一步，python3.8环境的Hoshino可能不是很完整，可以重新装一下Hoshino的requirements.txt。如果可以的话，把常用的python3.9环境的启动日志也贴一下吧。

**Comment by kushidou** [comment]
创建了一个python3.9的环境测试并适配了一下，您可以在安装好依赖环境后试用最新的代码。👉[454cecb](https://github.com/kushidou/bili-notice-hoshino/commit/454cecba76ef5b6fa21bd0ed47955dc124777f69)

如果还是无法加载、lssv无显示，麻烦提供一下py3.9环境的启动日志。

----- 

有关上一个issue提及的文件名、文件路径的问题，已经在readme中更新。

**Comment by 1055169799** [comment]
> 安装依赖 ![image](https://user-images.githubusercontent.com/41286675/176143702-f29a72c0-7a7f-4acb-8493-db064d42d3ff.png)
> 
> 安装cairo ![image](https://user-images.githubusercontent.com/41286675/176143888-ef3447ad-f465-4860-80fc-bf61c9deb178.png)
> 
> 原来已有的测试文件我没删 ![image](https://user-images.githubusercontent.com/41286675/176144239-29310481-02a2-455e-933f-da95d1fedcce.png)
> 
> 查看群内插件是没有发现 b站动态监视器 或是 b站动态监视器-测试版 这个插件的 ![image](https://user-images.githubusercontent.com/41286675/176145254-032820de-4851-43fa-9b04-ce06d15966f7.png)
> 
> 然后禁用掉多余的插件 ![image](https://user-images.githubusercontent.com/41286675/176146192-29ba9ce5-189d-4351-b046-fc1bcb30ab20.png)
> 
> 重新启动之后的显示：
> 
> C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup>py -3.9 run.py msgpack not installed, MsgPackSerializer unavailable [2022-06-28 17:35:32,416 config] WARNING: Not found config of "botmanage" [2022-06-28 17:35:32,416 config] WARNING: Not found config of "botchat" [2022-06-28 17:35:32,417 config] WARNING: Not found config of "bili-notice-hoshino" [2022-06-28 17:35:32,417 config] INFO: Succeeded to load config of "groupmaster" [2022-06-28 17:35:33,143 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.alert" [2022-06-28 17:35:33,145 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.broadcast" [2022-06-28 17:35:33,167 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.feedback" [2022-06-28 17:35:33,168 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.get_cqcode" [2022-06-28 17:35:33,168 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_invite" [2022-06-28 17:35:33,170 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_leave" [2022-06-28 17:35:33,171 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.help" [2022-06-28 17:35:33,172 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.log" [2022-06-28 17:35:33,176 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.ls" pygame 2.1.2 (SDL 2.0.18, Python 3.9.12) Hello from the pygame community. https://www.pygame.org/contribute.html [2022-06-28 17:35:33,232 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.service_manage" [2022-06-28 17:35:33,234 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.set_block" [2022-06-28 17:35:33,237 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.switch" [2022-06-28 17:35:33,250 hoshino] WARNING: Keyword trigger `正道的光` added multi handler: `chat_clanba` [2022-06-28 17:35:33,251 nonebot] INFO: Succeeded to import "hoshino.modules.botchat.botchat" [2022-06-28 17:35:33,376 nonebot] ERROR: Failed to import "hoshino.modules.bili-notice-hoshino.bili_notice_hoshino", error: No module named 'cairosvg' [2022-06-28 17:35:33,376 nonebot] ERROR: No module named 'cairosvg' Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin module = importlib.import_module(module_path) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 8, in from . import dymgr File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\dymgr.py", line 5, in from .res import drawCard File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 7, in from .getImg import get_ico, get_Image, round_mask File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\res\getImg.py", line 7, in import cairosvg as svg ModuleNotFoundError: No module named 'cairosvg' [2022-06-28 17:35:33,387 nonebot] ERROR: Failed to import "hoshino.modules.bili-notice-hoshino.bili_notice_test", error: No module named 'cairosvg' [2022-06-28 17:35:33,389 nonebot] ERROR: No module named 'cairosvg' Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin module = importlib.import_module(module_path) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\bili_notice_test.py", line 9, in from .res import drawCard File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 7, in from .getImg import get_ico, get_Image, round_mask File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\res\getImg.py", line 7, in import cairosvg as svg ModuleNotFoundError: No module named 'cairosvg' [2022-06-28 17:35:33,396 nonebot] ERROR: Failed to import "hoshino.modules.bili-notice-hoshino.dymgr", error: No module named 'cairosvg' [2022-06-28 17:35:33,396 nonebot] ERROR: No module named 'cairosvg' Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin module = importlib.import_module(module_path) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\dymgr.py", line 5, in from .res import drawCard File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\res\drawCard.py", line 7, in from .getImg import get_ico, get_Image, round_mask File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\res\getImg.py", line 7, in import cairosvg as svg ModuleNotFoundError: No module named 'cairosvg' [2022-06-28 17:35:33,406 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_abuse" [2022-06-28 17:35:33,408 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_msg_recall" [2022-06-28 17:35:33,409 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.group_notice" [2022-06-28 17:35:33,410 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.join_approve" [2022-06-28 17:35:33,412 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.random_repeater" [2022-06-28 17:35:33,414 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.sleeping_set" [2022-06-28 17:35:33,415 nonebot] INFO: Running on 127.0.0.1:8090 Running on http://127.0.0.1:8090 (CTRL + C to quit) [2022-06-28 17:35:33,419 nonebot] INFO: Scheduler started [2022-06-28 17:35:33,420] Running on http://127.0.0.1:8090 (CTRL + C to quit) [2022-06-28 17:35:34,115] 127.0.0.1:50085 GET /ws/ 1.1 101 - 1000
> 
> 查看插件列表依然是没有的 ![image](https://user-images.githubusercontent.com/41286675/176146732-c38d00a6-8e7d-4516-ae87-fb2bb7fcefce.png)

哈哈，我看了一下，原来是环境变量变成了py38了
改了一下变量，现在在用py39安装了
![image](https://user-images.githubusercontent.com/41286675/176194216-908b8308-0878-4fea-b0fa-e3d81cdc5d5f.png)
顺便也把所有插件的依赖重新安装了一下


现在启动之后下边的报错是

C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup>py -3.9 run.py
msgpack not installed, MsgPackSerializer unavailable
[2022-06-28 21:50:42,138 config] WARNING: Not found config of "music"
[2022-06-28 21:50:42,138 config] WARNING: Not found config of "translate"
[2022-06-28 21:50:42,139 config] WARNING: Not found config of "aichat"
[2022-06-28 21:50:42,139 config] WARNING: Not found config of "aircon"
[2022-06-28 21:50:42,139 config] WARNING: Not found config of "functions"
[2022-06-28 21:50:42,139 config] WARNING: Not found config of "Oreo"
[2022-06-28 21:50:42,139 config] WARNING: Not found config of "botchat"
[2022-06-28 21:50:42,140 config] WARNING: Not found config of "dasima"
[2022-06-28 21:50:42,140 config] WARNING: Not found config of "petpet"
[2022-06-28 21:50:42,140 config] WARNING: Not found config of "lifeRestart"
[2022-06-28 21:50:42,140 config] WARNING: Not found config of "traceanime"
[2022-06-28 21:50:42,140 config] WARNING: Not found config of "eqa"
[2022-06-28 21:50:42,141 config] WARNING: Not found config of "nowtime"
[2022-06-28 21:50:42,141 config] WARNING: Not found config of "steam"
[2022-06-28 21:50:42,141 config] WARNING: Not found config of "botmanage"
[2022-06-28 21:50:42,142 config] WARNING: Not found config of "shebot"
[2022-06-28 21:50:42,142 config] WARNING: Not found config of "egenshin"
[2022-06-28 21:50:42,142 config] WARNING: Not found config of "Bilibiliuid"
[2022-06-28 21:50:42,142 config] WARNING: Not found config of "revgif"
[2022-06-28 21:50:42,142 config] WARNING: Not found config of "KFCgenshin"
[2022-06-28 21:50:42,143 config] WARNING: Not found config of "advance_tarot"
[2022-06-28 21:50:42,143 config] WARNING: Not found config of "image_generator"
[2022-06-28 21:50:42,143 config] WARNING: Not found config of "generator"
[2022-06-28 21:50:42,143 config] WARNING: Not found config of "Genshinuid"
[2022-06-28 21:50:42,143 config] WARNING: Not found config of "bt_search"
[2022-06-28 21:50:42,144 config] WARNING: Not found config of "bili-notice-hoshino"
[2022-06-28 21:50:42,144 config] WARNING: Not found config of "yaowoyizhi"
[2022-06-28 21:50:42,144 config] WARNING: Not found config of "tarot"
[2022-06-28 21:50:42,144 config] WARNING: Not found config of "picfinder"
[2022-06-28 21:50:42,145 config] WARNING: Not found config of "hide_img"
[2022-06-28 21:50:42,145 config] WARNING: Not found config of "memberguess"
[2022-06-28 21:50:42,145 config] WARNING: Not found config of "dailywife"
[2022-06-28 21:50:42,145 config] WARNING: Not found config of "Genshin_Impact_bot"
[2022-06-28 21:50:42,146 config] WARNING: Not found config of "mahoocard"
[2022-06-28 21:50:42,146 config] WARNING: Not found config of "qrcode"
[2022-06-28 21:50:42,146 config] WARNING: Not found config of "emergeface"
[2022-06-28 21:50:42,147 config] INFO: Succeeded to load config of "groupmaster"
[2022-06-28 21:50:42,147 config] WARNING: Not found config of "baidu"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_cairo.py", line 15, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\run.py", line 1, in <module>
    import hoshino
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\__init__.py", line 54, in <module>
    from . import R
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\R.py", line 9, in <module>
    from hoshino import logger, util
  File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\util\__init__.py", line 13, in <module>
    from matplotlib import pyplot as plt
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 621, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 257, in switch_backend
    switch_backend(candidate)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 277, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\pyplot.py", line 278, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_gtk3agg.py", line 5, in <module>
    from . import backend_cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_cairo.py", line 21, in <module>
    import cairocffi as cairo
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e


然后我按照你上面的 单独安装一下日志里报缺失的cairo ==> pip install CairoSVG
显示的是

PS C:\Users\Administrator\Desktop> pip install CairoSVG
WARNING: Ignoring invalid distribution -pencv-python (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
Requirement already satisfied: CairoSVG in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (2.5.2)
Requirement already satisfied: cssselect2 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from CairoSVG) (0.6.0)
Requirement already satisfied: defusedxml in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from CairoSVG) (0.7.1)
Requirement already satisfied: tinycss2 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from CairoSVG) (1.1.1)
Requirement already satisfied: cairocffi in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from CairoSVG) (1.3.0)
Requirement already satisfied: pillow in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from CairoSVG) (8.3.2)
Requirement already satisfied: cffi>=1.1.0 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from cairocffi->CairoSVG) (1.15.0)
Requirement already satisfied: webencodings in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from cssselect2->CairoSVG) (0.5.1)
Requirement already satisfied: pycparser in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from cffi>=1.1.0->cairocffi->CairoSVG) (2.21)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages)
PS C:\Users\Administrator\Desktop>

**Comment by kushidou** [comment]
感谢协助提供日志。

从pip日志来看`cairoSVG`库已经是装上了，但是到导入模块的时候又会报`ModuleNotFoundError: No module named 'cairosvg'`，插件启动失败，也不会显示在lssv结果中了。

第二次发的py39环境的日志，好像依然是Hoshino启动的时候就出错了，和[1168159866](https://github.com/kushidou/bili-notice-hoshino/issues/6#issuecomment-1168159866)所解答的情况一样。可能是python3.8和3.9的环境没有严格隔离？

另外，两个python环境，模块的版本与我这边的都有所不同，比如`pillow==8.3.2`，而我这边的版本是`pillow==9.1.1`。我将我安装cairoSVG时的几个包的版本列出来，可以尝试安装指定的版本后启动一下。
```
cairoSVG (2.5.2)
pillow  (9.1.1)
tinycss2 (1.1.1)
defusedxml (0.7.1)
 cssselect2  (0.6.0)
cairocffi  (1.3.0)
cffi>=1.1.0 (1.15.0)
webencodings (0.5.1)
pycparser (2.21)

pip install pillow==9.1.1
```
----- 
另外提出一种方法，我在配置python3.9环境的时候遇到的：当时一些库版本不对也无法启动Hoshino，pip安装也是提示`Requirement already satisfied: `，于是我在pip安装的时候换了源地址，然后就好了，具体来说比如使用清华源重新下载模块：
```bash
pip install cairoSVG -i https://pypi.tuna.tsinghua.edu.cn/simple
```

最后祝你好运，能够先把机器人抢救起来😱

**Comment by 1055169799** [comment]
> 感谢协助提供日志。
> 
> 从pip日志来看`cairoSVG`库已经是装上了，但是到导入模块的时候又会报`ModuleNotFoundError: No module named 'cairosvg'`，插件启动失败，也不会显示在lssv结果中了。
> 
> 第二次发的py39环境的日志，好像依然是Hoshino启动的时候就出错了，和[1168159866](https://github.com/kushidou/bili-notice-hoshino/issues/6#issuecomment-1168159866)所解答的情况一样。可能是python3.8和3.9的环境没有严格隔离？
> 
> 另外，两个python环境，模块的版本与我这边的都有所不同，比如`pillow==8.3.2`，而我这边的版本是`pillow==9.1.1`。我将我安装cairoSVG时的几个包的版本列出来，可以尝试安装指定的版本后启动一下。
> ```
> cairoSVG (2.5.2)
> pillow  (9.1.1)
> tinycss2 (1.1.1)
> defusedxml (0.7.1)
>  cssselect2  (0.6.0)
> cairocffi  (1.3.0)
> cffi>=1.1.0 (1.15.0)
> webencodings (0.5.1)
> pycparser (2.21)
> 
> pip install pillow==9.1.1
> ```
> ----- 
> 另外提出一种方法，我在配置python3.9环境的时候遇到的：当时一些库版本不对也无法启动Hoshino，pip安装也是提示`Requirement already satisfied: `，于是我在pip安装的时候换了源地址，然后就好了，具体来说比如使用清华源重新下载模块：
> ```bash
> pip install cairoSVG -i https://pypi.tuna.tsinghua.edu.cn/simple
> ```
> 
> 最后祝你好运，能够先把机器人抢救起来😱

我这边用的也是清华库，我先试试吧，如果救不起来不置可否麻烦你帮忙远程解决一下。

**Comment by 1055169799** [comment]
安装你这边提供的一些依赖是成功的

C:\Users\Administrator\Desktop>py -3.9 -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: cairoSVG==2.5.2 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 1)) (2.5.2)
Requirement already satisfied: pillow==9.1.1 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 2)) (9.1.1)
Requirement already satisfied: tinycss2==1.1.1 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 3)) (1.1.1)
Requirement already satisfied: defusedxml==0.7.1 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 4)) (0.7.1)
Requirement already satisfied: cssselect2==0.6.0 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 5)) (0.6.0)
Requirement already satisfied: cairocffi==1.3.0 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 6)) (1.3.0)
Requirement already satisfied: cffi>=1.1.0==1.15.0 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 7)) (1.15.0)
Requirement already satisfied: webencodings==0.5.1 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 8)) (0.5.1)
Requirement already satisfied: pycparser==2.21 in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 9)) (2.21)

C:\Users\Administrator\Desktop>pause





启动后

报错内容大概是这个吧（我只知道看Error这个单词）
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\backends\backend_cairo.py", line 15, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'


 raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by 1055169799** [comment]
百度了一下，找到方法解决，启动成功了
![image](https://user-images.githubusercontent.com/41286675/176214604-57ad011c-b9bd-41d3-aca6-0d1b8125761c.png)
地址：https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

另外 lssv里也能看到插件了
![image](https://user-images.githubusercontent.com/41286675/176214732-6698cd74-67e2-4ba7-b8b9-f8e441ae9a96.png)
如果要启动正式版，是要把测试版的这个py文件删掉是吧?

**Comment by kushidou** [comment]
还在看Google和百度，想要解决的方法写了一半发现你能启动了😂

正常来讲，两个是共存的，看一下启动日志是不是正式版的插件加载报错了

**Comment by 1055169799** [comment]
> > 看了一下应该是这个
> > 
> > [2022-06-28 23:28:21,758 nonebot] ERROR: Failed to import "hoshino.modules.bili-notice-hoshino.bili_notice_hoshino", error: 'gbk' codec can't decode byte 0x88 in position 86: illegal multibyte sequence [2022-06-28 23:28:21,759 nonebot] ERROR: 'gbk' codec can't decode byte 0x88 in position 86: illegal multibyte sequence
> > 
> > File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\bili_notice_hoshino.py", line 8, in from . import dymgr File "C:\Users\Administrator\Desktop\noellebot\noelle-bot-setup\hoshino\modules\bili-notice-hoshino\dymgr.py", line 49, in up_group_info = json.load(f)
> 
> 
> 大概是因为我提供的模板文件是基于Linux系统，换行符是`\n`，而windows系统的换行符是`\r\n`，可以用**记事本**打开这个uppers里面所有的文件重新保存一次，然后用NotePad++检查一下换行符，并把编码改成UTF-8。
> 
> 

\n应该是没问题的，机器人本身和其它作者插件里我也看到过只用\n的。
另外我把所有能打开的文件都用UTF-8重新另存为覆盖了原文件，打开后依然还是上面那个报错

**Comment by kushidou** [comment]
> \n应该是没问题的，机器人本身和其它作者插件里我也看到过只用\n的。 另外我把所有能打开的文件都用UTF-8重新另存为覆盖了原文件，打开后依然还是上面那个报错

参考一下 [CSDN-Python读取文件出现‘gbk‘ codec can‘t decode byte 0xbf in position 2: illegal multibyte sequence‘](https://blog.csdn.net/weixin_38924500/article/details/112007564)

**Comment by 1055169799** [comment]
> > \n应该是没问题的，机器人本身和其它作者插件里我也看到过只用\n的。 另外我把所有能打开的文件都用UTF-8重新另存为覆盖了原文件，打开后依然还是上面那个报错
> 
> 参考一下 [CSDN-Python读取文件出现‘gbk‘ codec can‘t decode byte 0xbf in position 2: illegal multibyte sequence‘](https://blog.csdn.net/weixin_38924500/article/details/112007564)
> 

不明白

**Comment by kushidou** [comment]
文件读取已经添加强制utf-8编码方式，请更新到最新的代码尝试一下。

我之后在Windows平台搭建环境，集中修复一下插件的问题。

**Comment by kushidou** [comment]
恭喜啊，经过磕磕绊绊这个插件也算是能够启动了🎈

图片模糊的问题将在未来的版本予以解决（目前找到一个方案但是有些低效，需要查找其他方式，最后会与使用配置文件自定义参数的功能同步上线）。那么我关闭这个issue，并处理一下另一个issue报告的Windows平台的兼容性问题。
