### ISSUE TITLE
基于hoshinobot已经有比较好用的bilipush了哦，可以参考一下

### ISSUE THREAD

**Issue by scofieldle** [kushidou/bili-notice-hoshino#7]
bilipush有点小问题，一是服务器在海外会有延迟发送的情况，二是添加关注有时候会添加不上，报不存在up的情况，但是推送动态和直播都很正常。可以在这几个方面加加油/

**Comment by kushidou** [comment]
可以把bilipush的链接贴一下吗，我 ~~抄，不是~~ 学习一下。目前我还没有考虑到添加直播提醒的事项，等所有类型的动态卡片都做完后考虑添加一下。

**Comment by tuanzi66** [comment]
> bilipush有点小问题，一是服务器在海外会有延迟发送的情况，二是添加关注有时候会添加不上，报不存在up的情况，但是推送动态和直播都很正常。可以在这几个方面加加油/

那个关注不了up了，而且动态直播全都不能显示了

**Comment by zangxx66** [comment]
如果作者大大还没有想到推送直播动态的方案，可以参考一下HarukaBot，我的Bot就是把Haruka移植进去的

**Comment by kushidou** [comment]
> 如果作者大大还没有想到推送直播动态的方案，可以参考一下HarukaBot，我的Bot就是把Haruka移植进去的

倒也不是没想到方案，而是还没空去做这块，以及我在想要不要做成一个卡片推送的格式、怎么做这个格式。现在还有好几种动态的类型没做，比如H5活动的转发、番剧的分享等等。最近工作多了起来，摸鱼的时候只够修个bug，新功能还是先放一放。
